# Site settings
title: Luke Griffin
email: griffinluke321@gmail.com
url: https://github.com/LukeGrif
description: "Electronic and Computer Engineering graduate from the University of Limerick, now starting a PhD. I have hands-on experience in software engineering, data science, and semiconductor manufacturing, and have worked as a Teaching Assistant in ECE dept. Passionate about applying technology to real-world challenges and continuing to grow through research and innovation."
keywords: "Electronic and Computer Engineering"
skills: "Programming"
meta_author: Griffin Luke

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: “No man ever steps in the same river twice, for it is not the same river and he is not the same man.” – Heraclitus
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/luke-griffin-344854279/
  - title: github
    url: http://github.com/LukeGrif

# Postal address (add as many lines as necessary)
address:
  - line: <a href="https://www.google.com/maps/place/Lissycasey,+Co.+Clare/@52.7496975,-9.1567073,15z/data=!3m1!4b1!4m6!3m5!1s0x485b17725ff3cf57:0xc8229fe21b4f74fb!8m2!3d52.749243!4d-9.1469855!16zL20vMDJsd3B3?entry=ttu&g_ep=EgoyMDI1MDYyMi4wIKXMDSoASAFQAw%3D%3D">Lissycasey</a>
  - line: Co. Clare, Ireland

# Credits content
credits: 'Family & Friends'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
